### ISSUE TITLE
epel-formula/epel/init.sls - CenOS 7 EPEL Key changed but MD5 still old

### ISSUE THREAD

**Issue by ChrisTheTrainer** [saltstack-formulas/epel-formula#28]
Hello,

the md5sum change in https://github.com/saltstack-formulas/epel-formula/commit/8758b92a30ab02965371ce99a898986a5cc068c3 is wrong - the old key "58fa8ae27c89f37b08429f04fd4a88cc" needs to stay in there for the CentOS7 Epel key.

I get the error:
---------
          ID: install_pubkey_epel
    Function: file.managed
        Name: /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL
      Result: False
     Comment: File sum set for file /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL of 2d5d737d69703b926a2275e4c44a65e5 does not match real sum of 58fa8ae27c89f37b08429f04fd4a88cc
     Started: 07:47:17.230981
    Duration: 348.427 ms
     Changes:

Chris

**Comment by gravyboat** [comment]
@eliasp figured I would loop you in since you made this change. Did you encounter this at all?

**Comment by eliasp** [comment]
Oups, sorry… my bad… PR with fix will be there in a minute.

**Comment by eliasp** [comment]
Fix in https://github.com/saltstack-formulas/epel-formula/pull/29

**Comment by gravyboat** [comment]
Feel free to open this back up if you're still encountering the issue.

**Comment by ChrisTheTrainer** [comment]
that was quick - thank you
