### ISSUE TITLE
URL's require updating.

### ISSUE THREAD

**Issue by inderjitm** [saltstack-formulas/epel-formula#49]
Hi.

The formula is broken as it can't find the keys at the URL's specified.

Please amend the key location url's  to  https://fedoraproject.org from https://getfedora.org for o/s versions 5,6 and 7 in the file /epel/map.jinja

Thanks.

**Comment by aboe76** [comment]
@inderjitm can you make a PR for this?

**Comment by chorne-togetherwork** [comment]
@aboe76 - I have put in PR #50 to fix this.

**Comment by javierbertoli** [comment]
Fixed on #50
